version: '3'
services:
  database:
    image: mongo
    container_name: habitsync-mongo
    restart: always
    env_file: .env
    environment:
      - MONGO_INITDB_DATABASE=$MONGO_DB
      - MONGO_INITDB_ROOT_USERNAME=$MONGO_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD=$MONGO_PASSWORD
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo-js.js:ro
      - ./mongo-volume:/data/db
    ports:
      - '$MONGO_PORT:27017'
    command: [--auth]
